name: 'Sudsy Buddies :)'
favicon: null
layout_spectrum: 0.36462
typography_spectrum: 0.6009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#92495e'
    - '#c1b3d5'
    - '#000000'
    - '#3b3b3b'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
