name: 'Sudsy Buddies :)'
favicon: null
layout_spectrum: 0.49756
typography_spectrum: 0.6009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#449bb5'
    - '#68c39f'
    - '#043d5d'
    - '#ffffff'
    - '#b8d9e3'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
