name: Sudsy Buddies
favicon: null
layout_spectrum: 0.39394
typography_spectrum: 0.6009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff76df'
    - '#00a1e2'
    - '#ffffff'
    - '#5b5b5b'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
